### ISSUE TITLE
Error in 01a Dimensions - main plots 

### ISSUE THREAD

**Issue by hotsoupisgood** [CSSLab/social-dimensions#1]
Hi! I am trying to run through the jupyter notebooks in the `full_code/notebooks` section to reproduce some of the plots from you paper and I am encountering an error.  
 
In the first cell on 01a I get this error:
`FileNotFoundError: [Errno 2] No such file or directory: '/ada/projects/commembed/spark-3.0.0-preview2-bin-without-hadoop/./bin/spark-submit'`

It seems to be because I do not have the `/ada/projects/` directory setup. I was wondering how you set this directory up on your system? It is not exactly clear to me based on the code.

Thank you for your time.

**Comment by reidmcy** [comment]
You need to set the `SPARK_HOME` enviroment variable to wherever your spark is installed

https://github.com/CSSLab/social-dimensions/blob/93a0ac41dfe454e3c71124470a8254ca30cb33a3/full_code/commembed/data/__init__.py#L7

**Comment by hotsoupisgood** [comment]
Thank you for the response. I pointed the env variable to my installed spark/java and now it has gotten past that step.

~~I am having another issue while loading parquet:~~

~~`FileNotFoundError: [Errno 2] No such file or directory: '/ada/data/reddit/parquet/top_words_for_plotting.parquet'`~~

~~Are the parquet files posted somewhere? I can't seem to find them inside of the repository.~~

Just found the download.sh...
